### ISSUE TITLE
Updating page numbers

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#1038]
The bot's initial expansion found an "in press" version and allocated the page numbers "1-17" because the paper has 17 pages.
https://en.wikipedia.org/w/index.php?title=Nidelric&type=revision&diff=857985617&oldid=857985607

The paper is now out; I manually deleted the page range "1-17" and the bot expanded:
https://en.wikipedia.org/w/index.php?title=Nidelric&type=revision&diff=867677730&oldid=866911983

I wonder whether we need to mark journals as potentially incomplete if the page range starts at 1 (perhaps with the modifier that the publication date is in the last few years) to accommodate the possibility that the bot has picked up bad pre-pagination data?

**Comment by GlazerMann** [comment]
If (now-year < 2)
And if (first page is one)
And if (new pages do not start with 1)
Then Just do it

**Comment by GlazerMann** [comment]
#1090
