### ISSUE TITLE
Add DOAI open access URL when available

### ISSUE THREAD

**Issue by nemobis** [ms609/citation-bot#107]
If http://doai.io/ knows a redirect to a location other than dx.doi.org, add the doai.io URL to the "url" parameter.

**Comment by GlazerMann** [comment]
This is wrong place for bug reports.   Report them on Wikipedia bot oage

**Comment by nemobis** [comment]
> This is wrong place for bug reports. Report them on Wikipedia bot oage

You may want to disable the issue tracker on this project then.
