### ISSUE TITLE
Zotero issues

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#1189]
We should log the urls that zotero gets so that we can figure out a top 20 list of non journal cites to add to our non-journal list.

We get � from zotero.  Citoid gets this too.  ReFill does some of its own language detecting and avoids this problem.
https://github.com/zhaofengli/refill/blob/master/src/Reflinks/LinkHandlers/StandaloneLinkHandler.php

We might need cookies for some websites, not sure.

We should add more document types (patent, conference, etc.  there is a link in the code).

Our server code is at https://github.com/ms609/translation-server

**Comment by ms609** [comment]
I'm not going to have time to look into this for a while; feel free to look at the [server code](https://github.com/ms609/translation-server) and propose any changes there, which I can propagate to the server and feed back.

**Comment by GlazerMann** [comment]
@ms609 can we update the server.  The Wikipedia public API now gives many fewer  � than us

**Comment by ms609** [comment]
The server's updated, I  hope.  I'm not sure how I'd go about logging URLs -- suggestions welcome.
