### ISSUE TITLE
Can we get more CPU time on the tool server?

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#1246]
Or is it memory?
Or maybe we ask for too much memory?  I know we bumped up the default to deal with Regex errors - using array of Regex seems to have fixed that.  Although setting the max should not increase usage , I hope.

There is also talk that toolserver migration recently did horrible things, and it is not us

**Comment by nemobis** [comment]
How do we even know that we're using all the CPU/memory available? We may "just" need more workers, but it's not trivial if possible at all.
https://wikitech.wikimedia.org/wiki/Help:Toolforge/Kubernetes
https://www.mediawiki.org/wiki/Citoid has a `num_workers` variable , no idea if  http://tools.wmflabs.org/translation-server could.

**Comment by nemobis** [comment]
It might be a coincidence, or maybe Martin changed something else, but after f47b5cd26c890994f554b55cb223d0e83e81846e I notice that when I open https://tools.wmflabs.org/translation-server/web I always get a very quick response (404 of course) while formerly it always took ages.
