### ISSUE TITLE
Repeat calls to CrossRef

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#1276]
It looks from the output as though the bot's making an identical query to CrossRef twice.

![image](https://user-images.githubusercontent.com/1695515/52042247-9764bf00-2534-11e9-8307-2213bacd7e25.png)

Can we avoid these additional requests by flagging templates as having been expanded based on their DOI?

**Comment by GlazerMann** [comment]
https://github.com/ms609/citation-bot/pull/1281

**Comment by GlazerMann** [comment]
@ms609 I think I have a pull that does this now
