### ISSUE TITLE
Researchgate support

### ISSUE THREAD

**Issue by josve05a** [ms609/citation-bot#1427]
Bot doesn't expand info (such as DOI, PMID etc.) from Researchgate. Could any of these repositories help with this?

- [jaumebonet/RGcrawler](https://github.com/jaumebonet/RGcrawler)
- [moinfar/ResearchGate-Analyser](https://github.com/moinfar/ResearchGate-Analyser)

**Comment by GlazerMann** [comment]
The real problem is getting blocked as a bot.  We generally cannot even get any information from then at all.

**Comment by GlazerMann** [comment]
they even have an API for RIS data.  It works about five times and then we get blocked.

**Comment by GlazerMann** [comment]
if (preg_match("~^https?://(?:www.|)researchgate.net/[^\s]*publication/([0-9]+)~i", $url, $match)) {
     $ris_url = 'https://www.researchgate.net/publicliterature.PublicationHeaderDownloadCitation.downloadCitation.html?publicationUid=' . $match[1] . '&fileType=RIS&citationAndAbstract=false'; // Convert researchgate URL to give RIS information
   }
