### ISSUE TITLE
AdsAbs limit

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#1467]
Any thoughts as to what might be causing the below? Presumably we're maxing out our API token.  Is this a long-standing issue?  Is it our bot, or the AdsAbs server, that is the limiting factor? Is there a clear route to being permitted more requests?

! Error 999 in query_adsabs: Too many requests
 - URL was:  https://api.adsabs.harvard.edu/v1/search/query?q=title:%22%D0%A2%D1%83%D1%80%D0%BA%D0%BC%D0%B5%D0%BD%D0%B8%D1%81%D1%82%D0%B0%D0%BD%3A+%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B9+%D0%B2%D0%B5%D0%BA%22&fl=arxiv_class,author,bibcode,doi,doctype,identifier,issue,page,pub,pubdate,title,volume,year

**Comment by GlazerMann** [comment]
#1474 
These seems to happend whenever I do about 20 pulls at once.
