### ISSUE TITLE
Git will not update on toolservers 

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#1559]
probably good day to update dev version too

**Comment by GlazerMann** [comment]
@ms609 😿😪

**Comment by ms609** [comment]
`git pull` completed on `tools.citations`.

On `tools.citations-dev`, I got the error message

```
Your configuration specifies to merge with the ref 'refs/heads/development'
from the remote, but no such ref was fetched.
```

Have we deleted the development branch?  No time at the moment to investigate.
