### ISSUE TITLE
Git is gooned again

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#1582]

**Comment by GlazerMann** [comment]
@ms609 I don’t know anything about the configuration

**Comment by ms609** [comment]
A mystery to me – I've run a pull on the server.  Looks like I might need to keep doing so...

**Comment by GlazerMann** [comment]
@ms609 #1584   This should help some.

**Comment by ms609** [comment]
Got to the error: the PHP server no longer has the necessary permissions/password to edit the files.

Not got to the solution yet!
https://stackoverflow.com/questions/37752962 might help but doesn't mention a `passwd` file.  Not sure where this might lurk.

All I've got time for this morning¬

**Comment by GlazerMann** [comment]
@ms609 the new git pull script is a huge improvement in simplicity.

**Comment by ms609** [comment]
If only it worked! haha...

**Comment by GlazerMann** [comment]
Seems okay again

**Comment by ms609** [comment]
So it is, mysteriously... I guess that ToolForge must have fixed whatever was up at their end...

**Comment by GlazerMann** [comment]
And again.

**Comment by ms609** [comment]
Looked up-to-date when I manually pulled things through.  The new lock file looks a good idea though, if it works!
