### ISSUE TITLE
Combine requests to AdsAbs

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#1769]
To reduce the number of calls that we are making to AdsAbs, the maintainers have suggested that we check that we've made maximal use of boolean search operators.

For example, in `Template.php::expand_by_adsabs`, could we combine what is at present two searches into a single search that looks something like "title = XYZ OR (journal = X AND volume = 123)"?

I've had a stab at combining identifiers in #1771, but are there any other opportunities to combine queries?

**Comment by GlazerMann** [comment]
I cleaned it up and fixed it up.
