### ISSUE TITLE
Cache requests, particularly AdsAbs (and batch others?)

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#1770]
The AdsAbs maintainers have asked whether we might be able to cache AdsAbs search results in a local database.
It would take a bit of work to get a database up and running on the ToolForge server -- I might need a pointer in getting this set up -- but this could be a very useful change, speeding up the bot and reducing the number of external API calls required (not just to AdsAbs).  The implementation ought not to be too onerous, though we would have to give some thought to our test suite, which should test both the database AND the live APIs.

**Comment by GlazerMann** [comment]
Data would need to expire.
Failure to find something would expire faster than found data.
Data format and saving would require some significant recoding all over the place.
Zotero does caching.  Could just run everything through it, but we have lots of custom code for each data type that does good things, especially with GIGO.

**Comment by GlazerMann** [comment]
Crossref and doi.org valid/dead now cached.

**Comment by GlazerMann** [comment]
Also, some things perhaps can be batched?

**Comment by GlazerMann** [comment]
Just like DOIs, need to create array that maps bibcode to DOI and back again.  Would only use AdsAbs data and not trust existing Wikipedia data.  Would include NONE for ones that did not map.  This would be helpful for long category runs where lots of the same bibcodes and DOIs will show up again and again.

**Comment by GlazerMann** [comment]
And only DOIs that work
