### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#2098]
Why do we get asked to give the bot permission so often?

Also, can we downgrade the permissions needed by the bot since we do not edit pages as the user, but just need to verify the user is who they claim to be?  Will changing this allow us to have permission last longer (see above).

**Comment by ms609** [comment]
Not questions that I can answer – I agree that the frequent need for permissions is a pain.  I wonder whether there's a variable we can set for how long sessions remain active – presumably this is managed by the WP authenticator and is set by them for security reasons?

**Comment by GlazerMann** [comment]
@ms609 could you login to meta.wikimedia.org cite and lower the permissions we request from "Edit existing pages" to simply "basic rights".

**Comment by GlazerMann** [comment]
Perhaps we should use Special:OAuth/initiate instead

**Comment by davidbarratt** [comment]
So you can store the user's credentials in their browser for as long as you want, it shouldn't need to re-authenticate until the browser has dropped it.

**Comment by davidbarratt** [comment]
it looks like it's being set for a week though? https://github.com/ms609/citation-bot/blob/6df6bce3803e8a12dec842cce47717d65ec321f1/authenticate.php#L55

**Comment by davidbarratt** [comment]
Oh.... you ought *not* set the cookie, PHP does that for you. See: https://stackoverflow.com/a/8311400/864374

**Comment by GlazerMann** [comment]
#2176 is that better?

**Comment by GlazerMann** [comment]
#2177 then this? @davidbarratt

**Comment by GlazerMann** [comment]
user.ini was obviously not being used.  Fixed it, and now authentication failed. Working on that now:

**Comment by GlazerMann** [comment]
And fixed

**Comment by GlazerMann** [comment]
@davidbarratt  how does it look now?

**Comment by ms609** [comment]
Sorry it took me a while to respond to this – I struggled to find my login credentials.  Is any further action necessary from me?

**Comment by GlazerMann** [comment]
@ms609 can you downgrade the Meta wiki user request from “edit’ to just identify.  

Also but unrelated , I think the Dev bot should probably be updated to main branch.

**Comment by GlazerMann** [comment]
There are multiple APIs.  The one we use does not allow only verifying usernames at this point.  Added saving username to a cookie

**Comment by GlazerMann** [comment]
Setting Cookie helped a lot
