### ISSUE TITLE
update your script

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#2174]
Change edit=toolbar
to edit=Smith609
we are now trying to age where the edits came from (see process_page)

**Comment by GlazerMann** [comment]
#2173

**Comment by ms609** [comment]
I've edited https://en.wikipedia.org/w/index.php?title=User%3ASmith609%2Fcitations.js&type=revision&diff=920035054&oldid=856748059. Hope this is what you meant.
