### ISSUE TITLE
Web interface down

### ISSUE THREAD

**Issue by SednaBoo** [ms609/citation-bot#2362]
- Expected behaviour
Ability to use citation bot
- Actual behaviour
Go to:
https://tools.wmflabs.org/citations/
you get:

> No webservice

> The URL you have requested, https://tools.wmflabs.org/citations/, is not currently serviced.  If you have reached this page from somewhere else...

> This URI is managed by the citations tool, maintained by Dbarratt , Kaldari , Mattsenate , Maximilianklein , Smith609 .

> That tool might not have a web interface, or it may currently be disabled.

> If you're pretty sure this shouldn't be an error, you may wish to notify the tool's maintainers (above) about the error and how you ended up here.

> If you maintain this tool

> You have not enabled a web service for your tool, or it has stopped working because of a fatal error. Please check the error logs of your web service.

> Powered by Wikimedia Toolforge

- Link showing what goes wrong
https://tools.wmflabs.org/citations/

- How to replicate the issue
Go to website

**Comment by GlazerMann** [comment]
Hopefully Smith or someone with the power to fix it will. It's been down for a couple days.
https://en.wikipedia.org/wiki/User_talk:Citation_bot#Bot_down

**Comment by josve05a** [comment]
When the service is down you can always go on IRC and ask someone else to restart the service. (see https://wikitech.wikimedia.org/wiki/Nova_Resource:Tools.citations/SAL)

**Comment by GlazerMann** [comment]
Whoever does it will need to git reset the source I think

**Comment by SednaBoo** [comment]
I had asked on discord, after seeing no progress on the talk page.  Didn't know this was an IRC only thing

**Comment by ms609** [comment]
Seems to be working this morning.
https://en.wikipedia.org/w/index.php?title=Nectocotis&diff=prev&oldid=934401077

Please re-open if still not working for you!

**Comment by GlazerMann** [comment]
grrrrrrr

**Comment by GlazerMann** [comment]
https://en.wikipedia.org/wiki/User_talk:Krenair#Citation_bot

Fixed
