### ISSUE TITLE
Add SemanticScholar.org as a Citation Default Source

### ISSUE THREAD

**Issue by Jgordo72** [ms609/citation-bot#2475]
Following an initial conversation with @ms609 we are submitting a feature request to integrate the Citation Bot with Semantic Scholar's API (api.semanticscholar.org). In case you are not familiar with Semantic Scholar (semanticscholar.org), we are a free non-profit academic search and discovery engine developed by the Allen Institute for AI and over the past 4+ years we've developed a comprehensive literature graph that we provide programmatic access to with our API to advance open scientific search and discovery.

We are interested in adding our API as another data source to the Citation Bot in order to improve the availability of high quality links included in references in Wikipedia. Our API supports calls with DOIs and ArXiv IDs and we will be adding PubMed IDs next month. Here's the API call flow that we are proposing for the Citation Bot:

1. Citation Bot calls API with DOI/ArXiv ID/PubMed ID 
2. SemanticScholar API returns Paper/Title with "200" (Success Response) (let us know if paper title validation is sufficient to confirm that the referenced paper matches)
3. CitationBot creates a link from the title of the referenced work to the SemanticScholar paper detail page using our API redirect link structure (e.g. for a DOI-based link it looks like this: http://api.semanticscholar.org/10.1038/nrn3241)

Our goal is for these links to provide an additional discovery entry point for Wikipedia users so that they can explore our literature graph and find additional relevant information. You can find an example of one of our paper detail pages here: https://www.semanticscholar.org/paper/%22Why-Should-I-Trust-You%22%3A-Explaining-the-of-Any-Ribeiro-Singh/5091316bb1c6db6c6a813f4391911a5c311fdfe0.
Please let us know if this would be a useful enhancement for the Citation Bot and if yes, we are happy to have our developers submit a code change for approval (if that's the easiest way to proceed)

**Comment by GlazerMann** [comment]
I think that is a good idea.

**Comment by GlazerMann** [comment]
I think that is a good idea

Kurt Glaesemann, Ph.D.
Senior Software Engineer and Physical Chemist
P.S.  Brief and misspelled, because sent from iPhone.

**Comment by metasj** [comment]
+ a nice idea, especially where the version of record linked from the DOI is behind a paywall.  Can you filter up a link to an OA version of the underlying article where available?

**Comment by skohlmeier** [comment]
Thank you for the quick response and great to hear that you think this is a good idea @GlazerMann (also appreciate the support @metasj). We'll get a work item queued up for our engineering team on our side to contribute the code. With regards to also incorporating a link to the OA version this is something that's on our backlog and we can consider adding later.

**Comment by milescrawford** [comment]
I believe this can be closed - we now fall back to semanticscholar for OA urls.

We can definitely use the semanticscholar API for more information or link opportunities if we wish, and now there is demo code for doing so in the project. But this issue is probably closeable.
