### ISSUE TITLE
[Feature Request] Capitalize C in cite templates when  it is lowercase

### ISSUE THREAD

**Issue by RayBB** [ms609/citation-bot#2844]
Love your bot and think it works so great. Really appreciate all  the hard work you all  put into maintaining this :)

One small feature request is to capitalize the `c` in cite templates when you see that it's lowercase on a page. It's just a small thing but  it would be nice to add to help keep citations standard. [ReFill](https://en.wikipedia.org/wiki/User:Zhaofeng_Li/reFill#Options) does it right now but that tool has been buggy for me lately.

To be clear when you make new citations you're capitalizing it just like you should. I'm just asking to check on the old citations to make sure they're capitalizing the c in cite. Here's a screenshot of what I'm talking about.

![image](https://user-images.githubusercontent.com/921217/81133032-64229400-8f1e-11ea-8a0d-3c85a21b2553.png)

**Comment by GlazerMann** [comment]
Please post on   https://en.wikipedia.org/wiki/User_talk:Citation_bot   So there can be a discussion before we do this.  I agree this is a good idea.

**Comment by RayBB** [comment]
Thanks I posted it here: https://en.wikipedia.org/wiki/User_talk:Citation_bot#[Feature_request]_capitalize_C_in_cite_template

**Comment by GlazerMann** [comment]
That went worse than I expected.  I actually expected people to be in favor,  but apposed to a bot doing it without an approval process.  Ouch!

**Comment by GlazerMann** [comment]
" ReFill" gets away with it since it is not a bot
