### ISSUE TITLE
[Feature Request] Status Page

### ISSUE THREAD

**Issue by RayBB** [ms609/citation-bot#2846]
See: https://en.wikipedia.org/wiki/User_talk:Citation_bot#Create_a_status_page

**Comment by GlazerMann** [comment]
Would you get anything different than simply looking at 
https://en.wikipedia.org/wiki/Special:Contributions/Citation_bot

**Comment by GlazerMann** [comment]
Since neither of us know how to do this.  Closing item and leaving discussion on wikipedia open for help
