### ISSUE TITLE
Add API Key for Semantic Scholar API

### ISSUE THREAD

**Issue by skohlmeier** [ms609/citation-bot#2949]
Thank you for adding Semantic Scholar support back to the Citation Bot as discussed on the Citation Bot talk page (PR: https://github.com/ms609/citation-bot/pull/2943): https://en.wikipedia.org/wiki/User_talk:Citation_bot#Convert_semanticscholar_links_to_use_s2cid=

Since our initial integration earlier this year we've added rate limiting to the Semantic Scholar API to better manage API access, but we can lift those limits by providing you with an API key. Can you let us know what the best way is for us to securely send you the API key?

**Comment by GlazerMann** [comment]
Send the key to Martins college email address.  How do you add the API key to the request?

**Comment by skohlmeier** [comment]
Perfect, we'll send the API key over shortly. From an implementation perspective, the API key needs to be sent in the header of the request as x-api-key directed at https://partner.semanticscholar.org/ (note: this is a change since you are currently using https://api.semanticscholar.org). Please let us know if this won't work for you or if you have any questions!

**Comment by GlazerMann** [comment]
Will store in PHP_S2APIKEY
