### ISSUE TITLE
Need new oauth tokens

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#3140]
Need them to specify the new callback urls

**Comment by ms609** [comment]
I had a quick look but couldn't quickly find the link to set OAuth tokens.  Do you know where I need to head?

**Comment by GlazerMann** [comment]
https://meta.m.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose

**Comment by GlazerMann** [comment]
MediaWiki's OAuth system does not currently allow updating the registered URL after the initial request has been approved. After discussing various alternatives that could be used to work around this, it was decided that the easiest general solution to this problem would be to have Tool maintainers request new grants and be in control of which grant is used at runtime in their application.

To assist in getting new grants approved as quickly as reasonably possible, please use this process:

Keep the "Application name" and requested grants the same as your existing registration.
Increment the "Consumer version" number used in by the prior registration. For most Tools, using "2.0" as the new version number would be reasonable.
See the grant for the bash tool as an example.

If you are anxious to have the new grant approved quickly, you can join #wikimedia-cloud connect and ask for an expedited review with a message like "!help please approve <URL to your proposed grant>". This will not guarantee immediate action, but it can help a bit. If that succeeds, you can skip the usual Steward requests/Miscellaneous + {{oauthapprequest}} process.

**Comment by GlazerMann** [comment]
Example 

https://meta.m.wikimedia.org/wiki/Special:OAuthListConsumers/view/e73eaac293eaa1ba7f11952cd874f365

**Comment by GlazerMann** [comment]
Then put in if (!getenv('PHP_WP_OAUTH_CONSUMER') || !getenv('PHP_WP_OAUTH_SECRET')) {

**Comment by ms609** [comment]
Ta. Am I remembering rightly that I'll have to be logged in as Citation Bot to propose the token?

**Comment by GlazerMann** [comment]
Yes.  I think the user logged in has to be the user who is going to use them.

**Comment by GlazerMann** [comment]
https://github.com/ms609/citation-bot/issues/1767 Had lots of discussion

**Comment by GlazerMann** [comment]
I have changed the code so that it can use the old OAuth grant ----- as long as the toolserver redirects work.

**Comment by GlazerMann** [comment]
I requested and got new tokens.  Citation bot [1.2.0]
https://meta.wikimedia.org/w/index.php?title=Special:OAuthListConsumers/view/ea31bc18a6b8133fc0f29cf175d13a3a&name=&publisher=AManWithNoPlan&stage=-1
