### ISSUE TITLE
Translation server is down

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#3141]
Does it need restarted with canonical flag?

Is it some other setting that has a hostname hardwired?

Is is a firewall default setting on the new kubernetis?

**Comment by ms609** [comment]
Restarted with canonical flag.  
Stopping the webservice gives the "no webservice" page; starting the service briefly gives a 503 internal server error message, then goes to "Not found".

I re-pulled the translation server files from github to the `www` folder, and ran `npm start`. Now the server seems to be permanently Temporarily Unavailable...

**Comment by GlazerMann** [comment]
That’s all just really odd.

**Comment by GlazerMann** [comment]
Are there settings files that have paths or hostnames in them?

**Comment by GlazerMann** [comment]
https://phabricator.wikimedia.org/T261300

**Comment by GlazerMann** [comment]
We switch to wikipedia one.  Hoping for the best.  Thanks to nemobis

**Comment by nemobis** [comment]
Il 15/05/21 19:29, GlazerMann ha scritto:
> We switch to wikipedia one.  Hoping for the best.  Thanks to nemobis

Thank you very much for the speedy review!
