### ISSUE TITLE
Migrate Travis to dot com from dot org

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#3668]
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#does-the-migration-require-any-changes-in-our-travisyml

https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

**Comment by ms609** [comment]
I'm not sure that this is necessary, and there are some indications that it will be detrimental, as travis-ci.com seems to have recently introduced limits on the number of jobs that can be run per month.

**Comment by GlazerMann** [comment]
Travis-CI.ORG is being shutdown, and they have in the last week or two suddenly sucked. https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by ms609** [comment]
Thanks – I'd not received that e-mail, oddly.   Will get on the case.

**Comment by ms609** [comment]
Migrated to https://travis-ci.com/github/ms609/citation-bot ...

**Comment by GlazerMann** [comment]
It seems to not want to build.  Something about negative balance?  Do you need to "pick a plan".

**Comment by GlazerMann** [comment]
https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

The pain continues......

**Comment by ms609** [comment]
The "Free plan" seems not to include any OSS credits, oddly.  Is migration to Github actions feasible?

**Comment by GlazerMann** [comment]
It seems that the "free plan" is supposed to give you 10K free to start, but you also have to click the use paid for OS box.  

You can beg/ask for OSS credits. https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

 Github actions is certainly feasible, but I do know that the configuration will be different.

**Comment by GlazerMann** [comment]
https://dzone.com/articles/travis-ci-to-github-actions-what-to-know-about-mig
https://markphelps.me/2019/09/migrating-from-travis-to-github-actions/
https://bravelab.io/blog/migrating-from-travisci-to-github-actions-1/

**Comment by GlazerMann** [comment]
I did a second pull request from my repository copy instead and it ran, but github does not show it.

**Comment by GlazerMann** [comment]
@ms609 Pull request coming very soon with GitHub Actions

**Comment by GlazerMann** [comment]
@ms609 #3675 3675

**Comment by GlazerMann** [comment]
@ms609 - done
