### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#371]
Failures seem to differ by PHP version..
***PHP 7.0***
https://travis-ci.org/ms609/citation-bot/jobs/310495282

1) TemplateTest::testNewWikiText
Failed asserting that null matches expected 'Synthetic studies on β-lactam antibiotics. Part 10. Synthesis of 7β-&#91;2-carboxy-2-(4-hydroxyphenyl)acetamido&#93;-7.alpha.-methoxy-3-&#91;&#91;(1-methyl-1H-tetrazol-5-yl)thio&#93;methyl&#93;-1-oxa-1-dethia-3-cephem-4-carboxylic acid disodium salt (6059-S) and its related 1-oxacephems'.
/home/travis/build/ms609/citation-bot/tests/phpunit/TemplateTest.php:562

*** PHP 5 ***
There were 4 failures:
1) TemplateTest::testZooKeys
Failed asserting that null matches expected 'ZooKeys'.
/home/travis/build/ms609/citation-bot/tests/phpunit/TemplateTest.php:567
2) TemplateTest::testJustAnISBN
Failed asserting that null matches expected 'Explosives engineering'.
/home/travis/build/ms609/citation-bot/tests/phpunit/TemplateTest.php:687
3) TemplateTest::testJustAnOCLC
Failed asserting that null matches expected 'The Shreveport Plan: A Long-range Guide for the Future Development of Metropolitan Shreveport'.
/home/travis/build/ms609/citation-bot/tests/phpunit/TemplateTest.php:693
4) TemplateTest::testJustAnLCCN
Failed asserting that null matches expected 'Alternative Energy for Dummies'.
/home/travis/build/ms609/citation-bot/tests/phpunit/TemplateTest.php:699

**Comment by GlazerMann** [comment]
That’s strange.  I will look at and think about

**Comment by GlazerMann** [comment]
I have fixed the Google key with a pull.

**Comment by GlazerMann** [comment]
YEAH!!!!
