### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#393]
Doesn't seem to have been caused by code alterations this end, so presumably a remote server issue. Error seems to be intermittent.  Investigate cause?

Error message: 

```
1) TemplateTest::testCitoidJstorExpansion
Failed asserting that null matches expected '10.2307/3073767'.
/home/travis/build/ms609/citation-bot/tests/phpunit/TemplateTest.php:81
```

**Comment by GlazerMann** [comment]
We can scrape the data ourselves 
http://www.jstor.org/citation/ris/123445

**Comment by GlazerMann** [comment]
Add bad stables gives:
No RIS data found for 10.2307/i206866

good ones give:
Provider: JSTOR http://www.jstor.org
Database: JSTOR
Content: text/plain; charset="us-ascii"


TY  - JOUR
TI  - 
AU  - Tilly, Charles
A2  - Brezis, Elise S.
A2  - Temin, Peter
C1  - Full publication date: Spring, 2001
EP  - 623
IS  - 4
PB  - The MIT Press
PY  - 2001
RI  - Elites, Minorities and Economic Growth, Elise S. Brezis, Peter Temin
SN  - 00221953, 15309169
SP  - 622
T2  - The Journal of Interdisciplinary History
UR  - http://www.jstor.org/stable/206866
VL  - 31
ER  - 


Provider: JSTOR http://www.jstor.org
Database: JSTOR
Content: text/plain; charset="us-ascii"


TY  - JOUR
TI  - Western Loanwords in Modern Pashto
AU  - Penzl, Herbert
C1  - Full publication date: Jan. - Mar., 1961
DO  - 10.2307/594900
EP  - 52
IS  - 1
PB  - American Oriental Society
PY  - 1961
SN  - 00030279
SP  - 43
T2  - Journal of the American Oriental Society
UR  - http://www.jstor.org/stable/594900
VL  - 81
ER  -

**Comment by GlazerMann** [comment]
Quick historical perspective.  ReFill does jstor, and I tracked that back to Citoid by dredging through source code. I have repeated that in Citoid source and found jstor API they use.

**Comment by GlazerMann** [comment]
Pull request submitted.

**Comment by GlazerMann** [comment]
I DID NOT remove the Citoid calling code, since we might use it in the future.  Citoid (when it works) is very powerful and can do PMID, PMC, ISBN, URLS, etc.

**Comment by GlazerMann** [comment]
Fixed AdsAbs in another pull

**Comment by GlazerMann** [comment]
Https everywhere in another pull

**Comment by GlazerMann** [comment]
You can close this now 👍😎
