### ISSUE TITLE
Secret environment variables are missing during GitHub Actions - cannot test bibcode, etc.

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#3987]
Go into settings for the repository
Select secrets
Select actions
Add the secrets

**Comment by GlazerMann** [comment]
@ms609 - it looks like you need to add the "secrets" to the project.  Previously they were on travis-ci.org, before that shutdown.

**Comment by GlazerMann** [comment]
Go into settings for the repository
Select secrets
Select actions
Add the secrets

**Comment by roomiback** [comment]
Thanks

**Comment by GlazerMann** [comment]
Also need CODECOV_TOKEN from: https://app.codecov.io/gh/ms609/citation-bot/settings

**Comment by ms609** [comment]
`CODECOV_TOKEN` added to https://github.com/ms609/citation-bot/settings/secrets/actions; not clear which other secrets are required or where I'd find these

**Comment by GlazerMann** [comment]
@ms609 The PHP_ADSABSAPIKEY variable needs set.  It is the one in env.php:  putenv('PHP_ADSABSAPIKEY=D.....). I can email it to you if you have lost it).

**Comment by GlazerMann** [comment]
Here is a list of ones that I have set in my CLONE:
CODECOV_TOKEN
PHP_ADSABSAPIKEY
PHP_GOOGLEKEY
PHP_OAUTH_ACCESS_SECRET
PHP_OAUTH_ACCESS_TOKEN
PHP_OAUTH_CONSUMER_SECRET
PHP_OAUTH_CONSUMER_TOKEN
PHP_S2APIKEY
PHP_WP_OAUTH_CONSUMER
PHP_WP_OAUTH_SECRET

**Comment by GlazerMann** [comment]
@ms609  -  email sent

**Comment by ms609** [comment]
Secrets added.
