### ISSUE TITLE
Why does Citation bot try to fetch from dead URLs?

### ISSUE THREAD

**Issue by guyharris** [ms609/citation-bot#4070]
When I've used Citation bot in "Thorough mode" on various English-language Wikipedia pages, I get errors such as `Operation timed out after 5001 milliseconds with 0 bytes received   For URL: http://www.sun.com/software/javadesktopsystem/` on the "Oracle Solari" page, even though the citation that uses that URL is

```
{{cite web
  | url = http://www.sun.com/software/javadesktopsystem/
  | title = Sun Java Desktop System
  | publisher = Sun Microsystems Inc
  | date = May 22, 2006
  | access-date = March 10, 2007
  | archive-url = https://web.archive.org/web/20070315004836/http://www.sun.com/software/javadesktopsystem/
  | archive-date = March 15, 2007
}}
```

which doesn't have `url-status=live` and thus defaults to dead.  That particular URL happens to redirect to https://www.oracle.com/it-infrastructure/, so it doesn't time out due to a dead server, but it still takes more time than is necessary and doesn't provide the page in question.  Other dead links might be to dead servers, so that the error is a timeout.

**Comment by GlazerMann** [comment]
This is not the correct place for bug reports.  This page is ignored
