### ISSUE TITLE
vauthors test cases

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4284]
@GlazerMann - can you please add a few vauthors test cases, so we could improve the feature? I tried to add the test cases, but didn't understand on how to do that properly. For example, if we have just {{cite journal|doi=10.15347/WJM/2023.003}} and the page has {{cs1 config|name-list-style=vanc}}, the bot should at, among other, `vauthors = Masiutin MG, Yadav MK`. Another example, {{cite journal|pmid=35987379}}, should also add `vauthors = Masiutin MG, Yadav MK`. Probably, the bot currently does not properly resolve the middle name letter for vauthors. Can you please add tests, and I will improve the bot? Now it seems to add `vauthors = Masiutin M, Yadav M`, i.e. only the last name and the first character from the first name, but it also add a first character from the middle name. Thank you in advance!

**Comment by GlazerMann** [comment]
You have to look at the tests in Page tests, since the tests are for "pages" and not single templates.

**Comment by maximmasiutin** [comment]
> You have to look at the tests in Page tests, since the tests are for "pages" and not single templates.

Thank you! I found the test cases and they are very good, still, would you mind if I add a few more tests? I also have a question on intermittent errors.

Why there was a one-off error at https://github.com/ms609/citation-bot/actions/runs/7269774953/job/19807906987
on PageTest::testVancNames2 ?

There were no such error in other runs, such as https://github.com/ms609/citation-bot/actions/runs/7271098765/job/19811181480

Also, the bot didn't display any warning. How could we debug such cases?

**Comment by GlazerMann** [comment]
Not sure about intermittent errors.  Some times the remote databases do not send any data.

**Comment by maximmasiutin** [comment]
@GlazerMann  - you already made very good test cases for vauthors, no additional test cases are needed so far. Thank you very much!
