### ISSUE TITLE
Bot removes a pipeline from double pipelines in templates such as {{#invoke:Infobox_gene||getTemplateData|QID=Q18031857}} causing error in those templates

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4302]
The bot removes a pipeline from double pipelines in templates such as {{#invoke:Infobox_gene||getTemplateData|QID=Q18031857}} causing error in those templates

See example at https://en.wikipedia.org/w/index.php?title=TCEA1&oldid=prev&diff=1191681094

It was a template:

`{{#invoke:Infobox_gene||getTemplateData|QID=Q18031857}}``

The bot replaced it to:

`{{#invoke:Infobox_gene|getTemplateData|QID=Q18031857}}``

However, it should have not replaced `||` to `|` in this template.

What can you suggest?

**Comment by GlazerMann** [comment]
Not a problem with newer bot versions

**Comment by maximmasiutin** [comment]
@GlazerMann - thank you very much! I tried on today's master branch and the bot works correctly. Thank you for the fix. That's how I tried:
```
php ./process_page.php "TCEA1" --slow --savetofiles
```

Thank you very much again!
