### ISSUE TITLE
Improper title logging

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4404]
I have noticed that citations bot logs title as multiline when the title contains subscript or superscript characters. This can be reproduced on page "Vancomycin" that contains references to https://www.pnas.org/doi/full/10.1073/pnas.1704125114 with title "Peripheral modifications of [Ψ[CH<sub>2</sub>NH]Tpg<sup>4</sup>]vancomycin with added synergistic mechanisms of action provide durable and potent antibiotics".

To reproduce, run `php process_page.php "Vancomycin"`

You will get the following output, among others:
```
   !CrossRef title did not match existing title: doi:10.1073/pnas.1704125114
   >  Possible new title:
            Peripheral modifications of [Ψ[CH
            2
            NH]Tpg
            4
            ]vancomycin with added synergistic mechanisms of action provide durable and potent antibiotics

```
I expect that the bot display it the following way:
```
>  Possible new title:
            Peripheral modifications of [Ψ[CH2NH]Tpg4]vancomycin with added synergistic mechanisms of action provide durable and potent antibiotics

**Comment by GlazerMann** [comment]
The title we get oddly includes the line-feeds.  https://api.crossref.org/works/10.1073/pnas.1704125114  I have added code to remove those from the output.

**Comment by maximmasiutin** [comment]
I checked again and the title is still echoed with crlfs, see 
```
php process_page.php "Vancomycin" --slow
```

It will show
```
   >  Possible new title: 
            Peripheral modifications of [Ψ[CH
            2
            NH]Tpg
            4
            ]vancomycin with added synergistic mechanisms of action provide durable and potent antibiotics
          
   >  Existing old title: 4]vancomycin with added synergistic mechanisms of action provide durable and potent antibiotics
```

Maybe we should remove all cr/lf characters from title before echoing title?
