### ISSUE TITLE
PHP Deprecated:  Creation of dynamic property MediaWiki\OAuthClient\Request::$base_string is deprecated in HmacSha1.php

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4406]
I'm using oauthclient library version 2.0.0 as prescribed in the readme (`composer require mediawiki/oauthclient:2.0.0`) and php 8.3.2. With these settings, whenever bot writes a page, I'm getting the following php deprecaded messages, see example output of `php process_page.php "Xerces blue" --slow`:

```
>Writing to Xerces blue... 

PHP Deprecated:  Creation of dynamic property MediaWiki\OAuthClient\Request::$base_string is deprecated in citation-bot/vendor/mediawiki/oauthclient/src/SignatureMethod/HmacSha1.php on line 65

Deprecated: Creation of dynamic property MediaWiki\OAuthClient\Request::$base_string is deprecated in citation-bot/vendor/mediawiki/oauthclient/src/SignatureMethod/HmacSha1.php on line 65

PHP Deprecated:  Creation of dynamic property MediaWiki\OAuthClient\Request::$base_string is deprecated in citation-bot/vendor/mediawiki/oauthclint/src/SignatureMethod/HmacSha1.php on line 65

Deprecated: Creation of dynamic property MediaWiki\OAuthClient\Request::$base_string is deprecated in citation-bot/vendor/mediawiki/oauthclient/src/SignatureMethod/HmacSha1.php on line 65

https://en.wikipedia.org/w/index.php?title=Xerces+blue&diff=prev&oldid=120447238                                               7
```

This message can also be seen in the github runner, e.g. see [https://github.com/ms609/citation-bot/actions/runs/7807608076/job/21296304922?pr=4405]. You will be able to find the following lines there:

```
PHP Deprecated:  Creation of dynamic property MediaWiki\OAuthClient\Request::$base_string is deprecated in /home/runner/work/citation-bot/citation-bot/vendor/mediawiki/oauthclient/src/SignatureMethod/HmacSha1.php
```

Maybe we should switch to latest version of the MediaWiki OAuthClient where this "deprecated" code is not used.

**Comment by maximmasiutin** [comment]
Maybe we could fix that and submit a pull request? Do you have any idea on how to fix that?

**Comment by GlazerMann** [comment]
You have to submit pull requests this way:  https://github.com/wikimedia/mediawiki-oauthclient-php/pull/10

**Comment by GlazerMann** [comment]
The solution is to add this to Client.php:
	/**
	 * @var array
	 */
	protected $extraParams;

Add to add this to Request.php
	/**
	 * @var string
	 */
	protected $base_string;

I personally would remove the setting of variables, but I assume they exist for some reason.

**Comment by maximmasiutin** [comment]
Probably this "$base_string" is not used at all, at least in our citation bot. It may be used in other programs though. I would have removed it at all. But probably safer will be to define it as you recommend.

**Comment by maximmasiutin** [comment]
I saw you submitted the pull request via GitHub, but they asked to submit to Gerrit.

I fount https://gerrit.wikimedia.org/r/admin/repos/mediawiki/oauthclient-php,general

Did you submit there? Or let me submit that your proposed code?
