### ISSUE TITLE
Wholoe bot exitst on a page "Symplocamide A"

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4423]
Hello, can you please try:

```
 php process_page.php "Symplocamide A" --savetofiles
```

I tried various versions from latest master during last 3 weeks, the whole bot exists on processing the page "Symplocamide A" almost immediatly, it prints the following:

```
   >Will skip the search for new bibcodes and the expanding of URLS in non-slow mode
[00:59:18] Processing page Symplocamide A...


>Remedial work to prepare citations
   !No corpusId found from semanticscholar for https://api.semanticscholar.org/v1/paper/URL:https%3A%2F%2Fsemanticscholar.org%2Fpaper%2F7f667a48bb46f64873ef454a1fd5bd40d9b7e762%
```

and exits, even if I pass multiple pages, it just halts.

**Comment by GlazerMann** [comment]
Which PHP version?

**Comment by GlazerMann** [comment]
I cannot reproduce it

**Comment by maximmasiutin** [comment]
I am using php 8.3 on MacOs. Are there any debug settings that you can recommend to see what is happening?

**Comment by maximmasiutin** [comment]
I run today again and this 

> Which PHP version? I could not reproduce. I have seen oddities when the php is missing some multibyte character modules, but that was never a fail, just garbage titles.

Can you please try again with the `--savetofiles` parameter, since somebody fixed the page today. I gave version details in my previous message.

**Comment by GlazerMann** [comment]
That was flagged as a minor_error, which crashes the command line so we have time to investigate.  It is now a warning.
