### ISSUE TITLE
Do not echo title suggestions when suggested title is a substring of an existing title, case-insensitive?

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4444]
When running from command-line, we are getting "CrossRef title did not match existing title" messages like the following:

```
   !CrossRef title did not match existing title: doi:10.1002/phar.2388
   >  Possible new title: Vancomycin‐Induced Kidney Injury: Animal Models of Toxicodynamics, Mechanisms of Injury, Human Translation, and Potential Strategies for Prevention
   >  Existing old title: Vancomycin-Induced Kidney Injury: Animal Models of Toxicodynamics, Mechanisms of Injury, Human Translation, and Potential Strategies for Prevention. Pharmacotherapy.
```
(to reproduce, run `php process_page "Vancomycin" --slow`) -- in this case, no "CrossRef title did not match existing title" at all should be reported.

What do you think that if a "Possible new title" is a substring of "Existing old title", case-insensitive, such as in this case, such case should not be echoed?

Here is another example: `php process_page "Titanium(III) chloride" --slow`

```
   !CrossRef title did not match existing title: doi:10.1002/9780470132524.ch31
   >  Possible new title: Inorganic Syntheses
   >  Possible new title: 31. Tetragtdrfuran Complexes of Selected Early Transition Metals.
   >  Existing old title: Tetrahydrofuran Complexes of Selected Early Transition Metals
   >  Existing old title: [[Inorganic Syntheses]]
```

In this case, "CrossRef title did not match existing title" should be reported, but only with 
```
   >  Possible new title: 31. Tetragtdrfuran Complexes of Selected Early Transition Metals.
   >  Existing old title: Tetrahydrofuran Complexes of Selected Early Transition Metals
```
whereas the lines with "Inorganic Syntheses" should not be reported, because "Possible new title" is fully inside the "Existing old title".

Here, "Inorganic Syntheses" is a "series", not "title", and it should be echoed as "series", not as "title".

**Comment by GlazerMann** [comment]
I have improved the matching code.  Secondly, I went and fixed on the page the two bogus titles.

**Comment by maximmasiutin** [comment]
Thank you, now the citation bot updated the title and the chapte for "Titanium(III) chloride", and the messages about titles for "Vancomycin" are now also OK, thank you for the quick fix of the echoing of the information.
