### ISSUE TITLE
CITATION_BOT_PLACEHOLDER_TEMPLATE entries in the echo log

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4455]
There are "CITATION_BOT_PLACEHOLDER_TEMPLATE" entries in the echo log on some articles. For example, on processing the page "1,10-Phenanthroline" you will see lines such as the following:

```
   >  Possible new title: 43. Attempts to find new antimalarials. Part XXIV. Derivatives of o-phenanthroline (7 : 8 : 3′ : 2′-pyridoquinoline)
   >  Existing old title: 43. Attempts to find new antimalarials. Part XXIV. Derivatives of o-phenanthroline (7 : 8 : 3# # # CITATION_BOT_PLACEHOLDER_TEMPLATE 2 # # # : 2# # # CITATION_BOT_PLACEHOLDER_TEMPLATE 2 # # #-pyridoquinoline)
```

To reproduce the issue, run the bot for one or several the following pages using the following command line:
```
php expand_page.php "(307261) 2002 MS4|1,10-Phenanthroline|1,4,7-Trimethyl-1,4,7-triazacyclononane|Crown Jewel (NASCAR)|Androgen backdoor pathway|CYP3A4|Human multitasking" --slow
```

**Comment by GlazerMann** [comment]
That is because the existing title is: 43. Attempts to find new antimalarials. Part XXIV. Derivatives of o-phenanthroline (7 : 8 : 3{{prime}} : 2{{prime}}-pyridoquinoline), which has templates in it.  I will take some effort to expand those properly in the text comparision.

**Comment by maximmasiutin** [comment]
Thank you for letting me know. Although this issue is minor, as it is only echoed in the output.

**Comment by GlazerMann** [comment]
Now uses the ugly � for any templates in output and comparisons.  Not a perfect solution, but good enough for a rare problem.

**Comment by maximmasiutin** [comment]
Thank you! Now it is very good:

```
   >  Possible new title: 43. Attempts to find new antimalarials. Part XXIV. Derivatives of o-phenanthroline (7 : 8 : 3′ : 2′-pyridoquinoline)
   >  Existing old title: 43. Attempts to find new antimalarials. Part XXIV. Derivatives of o-phenanthroline (7 : 8 : 3� : 2�-pyridoquinoline)
```
