### ISSUE TITLE
Rename the misleading function curl_init_array to bot_curl_init

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4464]
The current name of the function to initialize the curl array, `curl_init_array` is misleading. The prefix `curl_` suggests that this function is from curl API. Please consider renaming it to `bot_curl_init`, analoguosly to `bot_curl_exec`.

**Comment by GlazerMann** [comment]
I would be money that within five years, there will be an actual curl_init_array() function added to curl, so you are correct.
