### ISSUE TITLE
Alternative memory measurements in CodeCoverage

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4471]
Please consider changing memory measurements in CodeCoverage, as it seems that when the bot is running a long batch, the memory is taken by caching hashes that cache DOIs and other items, so that memory usage of above 9MB is normal and not caused by a page processing, but by caching probably, maybe it is worth to display not only total memory use but the sizes or number of elements in these caching arrays for better analysis, and the counter in the batch, only the position of this page in the batch (the total batch size is not needed for logging).

Otherwise, these messages of memory usage of above 9MB have low diagnostic value, they are misleading and distracting from real stuff.

**Comment by GlazerMann** [comment]
I have upped the value to 24MB based upon the level of logging.

**Comment by maximmasiutin** [comment]
> I have upped the value to 24MB based upon the level of logging.

Yes, that makes sense!
