### ISSUE TITLE
An environment variable or a command line option to add/check Semantic Scholar IDs and use Semantic Scholar API

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4474]
There were a feature in the citations bot to add/check Semantic Scholar IDs and use Semantic Scholar API, but you recently removed this function. Can you please add a command line option or an option passed via the environment variable to get back to the functionality to add/check Semantic Scholar IDs and use Semantic Scholar API as it was before, so, if needed, I could run the bot on particular pages where  Semantic Scholar IDs are needed? Can you please make that although disabled by default, but optionally possible to turn on?

**Comment by maximmasiutin** [comment]
I saw some people asked you on Wikipedia to not add the s2cid attribute to citations when expanding citations; still, I would prefer an option to allow the s2cid attribute addition.

**Comment by maximmasiutin** [comment]
I didn't know that, I think we should document better the behaviour of the bot so that people could understand better how it works, to avoid controversy. What if we expand the text at https://en.wikipedia.org/wiki/User:Citation_bot/use
# Add s2cid as the attribute that it can read to find other attributes, i.e. in "Now you can type or paste in only the [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier), [PMID](https://en.wikipedia.org/wiki/PMID), or," add s2cid;
# Make a section that describes what attributes does the bot adds, some attributes will be just enumerated (for now), other will have a bigger description.

If you are OK with that, in principle, I could try to add information to https://en.wikipedia.org/wiki/User:Citation_bot/use and you will review/edit

**Comment by GlazerMann** [comment]
Please update the documentation tohttps://en.wikipedia.org/w/index.php?title=User:Citation_bot/use&curid=17593553&diff=1219397933&oldid=1190399479

**Comment by maximmasiutin** [comment]
Thank you, I hope that by making edits to https://en.wikipedia.org/wiki/User:Citation_bot/use I address all the concerns I mention in this topic.

**Comment by maximmasiutin** [comment]
@GlazerMann, I updated the documentation, although it was a very minor update needed, as the update was related to the Semantic Scholar IDs only. Still, could you please implement an option such as via an environment variable, to force insertion of Semantic Scholar IDs to citation even for the cases when the Semantic Scholar entry for the article does not contain anything useful?
