### ISSUE TITLE
Support for bare URL expansion from sciencedirect.com

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4477]
Please consider support for Support for bare URL expansion from sciencedirect.com, e.g. `https://www.sciencedirect.com/science/article/pii/S0960076019302699`

These sciencedirect articles have DOI, e.g., in this case, `https://doi.org/10.1016/j.jsbmb.2019.105494` which can be further used to expand these URLs.

The example pages where you can find these sciencedirect.com links are:
1. https://en.wikipedia.org/wiki/AKR1C2
2. https://en.wikipedia.org/wiki/AKR1C3
3. https://en.wikipedia.org/wiki/AKR1C4

**Comment by GlazerMann** [comment]
It already does, but it is just very unreliable.  I will look at adding the new api https://dev.elsevier.com/documentation/ArticleMetadataAPI.wadl

**Comment by GlazerMann** [comment]
Sometimes Zotero gets stuff some times it does not: https://en.wikipedia.org/w/index.php?title=AKR1C2&diff=1217957773&oldid=1217926966

**Comment by maximmasiutin** [comment]
Thank you! Should we close this issue and create a new one "adding the new api https://dev.elsevier.com/documentation/ArticleMetadataAPI.wadl" so we will not forget about that in the future?
