### ISSUE TITLE
Template::check_url

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#458]
Function disabled: comment reads:
    /*  Disable; to re-enable, we should log possible 404s and check back later.
     * Also, dead-link notifications should be placed ''after'', not within, the template.

**Comment by josve05a** [comment]
Probably not the right place to mention this, but https://github.com/wikimedia/DeadlinkChecker is a good repository/dependency to check if a link is dead.

**Comment by ms609** [comment]
Handy, thanks!

**Comment by GlazerMann** [comment]
@ms609 putting this in the code

**Comment by GlazerMann** [comment]
Should we add dead url tags when we find url titles like “buy this domain now!”

**Comment by GlazerMann** [comment]
#1606 Should we close this issue, after this documentation is added.  I really do not feel like beating my head against the mobs on this issue at this time.

**Comment by GlazerMann** [comment]
I will close since this is all documented in the source code and at this point in time, there are other bots that do this.
