### ISSUE TITLE
BibCodes

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#467]
email adshelp@cfa.harvard.edu and ask for bigger limits

Get second key for testing: during active development we can kill the limits fast

**Comment by ms609** [comment]
Opened e-mail correspondence this morning; ads are looking into what can be done to help.

**Comment by ms609** [comment]
Our daily allowance has been upped by an order of magnitude: yay!
Meanwhile, I've found some opportunities to reduce the number of requests that we make, listed as issues.
More generally it might be time to refactor the code to make fewer calls to external APIs, i.e. to apply "expand" to all citation templates simultaneously.
