### ISSUE TITLE
Translation for $edit_summary_end

### ISSUE THREAD

**Issue by In1quity** [ms609/citation-bot#4710]
Hi again, I figured out why some of the lines were left in English. The end of the description is in another variable: $edit_summary_end
https://github.com/ms609/citation-bot/blob/64bbc5474aaf3474ad3c812e3201bc107161612e/Page.php#L736
https://github.com/ms609/citation-bot/blob/64bbc5474aaf3474ad3c812e3201bc107161612e/process_page.php#L59

**Comment by GlazerMann** [comment]
Closing, since I have made a pull request.

**Comment by In1quity** [comment]
It works! Thanks!
