### ISSUE TITLE
Disable date conversion for ruwiki

### ISSUE THREAD

**Issue by In1quity** [ms609/citation-bot#4712]
Hi! Ruwiki has adopted a convention for service dates and times, which requires all dates to be stored in ISO. The bot converts these dates, in particular YYYY-MM back to English (look at line 182): https://ru.wikipedia.org/w/index.php?diff=141745079&oldid=141029855&title=Домашнее_насилие.

**Comment by GlazerMann** [comment]
Working on it. https://github.com/ms609/citation-bot/pull/4713

**Comment by In1quity** [comment]
Thanks! :)
