### ISSUE TITLE
Do not replace double angle quotes in ruwiki

### ISSUE THREAD

**Issue by In1quity** [ms609/citation-bot#4726]
Hi! Can we remove double angle quotes from the regex for ruwiki? Since these quotes are the main ones for us.
https://github.com/ms609/citation-bot/blob/1453b98ee67e24943908b34acdd455e406200216/expandFns.php#L835
https://github.com/ms609/citation-bot/blob/1453b98ee67e24943908b34acdd455e406200216/expandFns.php#L839

**Comment by GlazerMann** [comment]
I think this should fix it https://github.com/ms609/citation-bot/commit/41a5a4b643a868e7427c1899e40279b80680f9c0

**Comment by In1quity** [comment]
It works! Thanks! :)
