### ISSUE TITLE
Combine AdsAbs search

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#479]
In function `expand_by_adsabs`, a miss on a DOI search will trigger a wildcard parameter search.
Could both searches be performed by a single call to the AdsAbs API?

**Comment by GlazerMann** [comment]
No.  I looked into it.  The operation in the search is AND, so if doi=10.xxx fails then doi=10.xx&year=2000 is not gonna hit anything.

**Comment by ms609** [comment]
It does look that way, doesn't it.  I wonder what was being referred to when AdsAbs asked us to reduce the number of queries by submitting them in batches: there's big-query to expand from many bibcodes at once (now implemented in dev branch), but that's all I can find in that direction.
