### ISSUE TITLE
Edit summary incomplete

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#496]
Edit summary reads `Alter: . Add. Removed parameters. ` in [this edit](https://en.wikipedia.org/w/index.php?title=L%C3%A1szl%C3%B3_%C3%81goston&diff=prev&oldid=853215943)

**Comment by GlazerMann** [comment]
Probably should create a function to change name.
It should NOT change the name if it is ‘citation’
Verify that it really is changing it before setting the ‘modification’ var

**Comment by GlazerMann** [comment]
https://github.com/ms609/citation-bot/pull/511
