### ISSUE TITLE
AdsAbs key environment variable not set on tool server

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#499]
Expand citation: 
- Checking AdsAbs database
x PHP_ADSABSAPIKEY environment variable not set. Cannot query AdsAbs. [..> yadsabs]: no record retrieved. [..> rossref]
- Checking CrossRef database for doi.  [..> indpmid]
- Searching PubMed...  nothing found.

**Comment by ms609** [comment]
Cannot replicate.  How are you expanding the citation?  Can you give a full URL and the page that is being expanded?

**Comment by GlazerMann** [comment]
https://en.wikipedia.org/wiki/User:AManWithNoPlan/sandbox2

**Comment by GlazerMann** [comment]
All three methods fail for me

**Comment by GlazerMann** [comment]
https://tools.wmflabs.org/citations/doibot.php?edit=toolbar&slow=1&user=AManWithNoPlan&page=User%3AAManWithNoPlan%2Fsandbox2

**Comment by GlazerMann** [comment]
Any progress on this??
