### ISSUE TITLE
Please wait... message not disappearing

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#505]
After entering a page name at https://tools.wmflabs.org/citations/doibot.html and clicking submit, the "please wait" message appears but nothing else happens.  Can we revert the commit that introduced this message so that we revert to the old behaviour?

**Comment by GlazerMann** [comment]
It works for me, but feel free to revert.

**Comment by GlazerMann** [comment]
I think I have figured it out and submitted a pull

**Comment by ms609** [comment]
Still not working for me.
