### ISSUE TITLE
Don't stack [[WP:UCB|Assisted by Citation bot]]

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#573]
When launching the bot from the Wikipedia page edit textbox, then running the bot again, the message [[WP:UCB|Assisted by Citation bot]] | [[WP:UCB|Assisted by Citation bot]] | [[WP:UCB|Assisted by Citation bot]] stacks up at the end of the edit summary.  Only add it once.

**Comment by GlazerMann** [comment]
Pull done

**Comment by GlazerMann** [comment]
Oh yeah.  Do not forget to close issues...
