### ISSUE TITLE
maintain_files not pushing

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#673]
See https://travis-ci.org/ms609/citation-bot/jobs/420424097

**Comment by GlazerMann** [comment]
Perhaps we should have the auto format should run every night or something

**Comment by GlazerMann** [comment]
I should note that running  this on pulls makes it really hard to see what changed

**Comment by GlazerMann** [comment]
This is probably because you don’t do a git pull on Wikipedia before doing the maintenance.  It just keeps processing the same old files.  YML should:
Gitpull 
Maintenance 
Gitpull again

**Comment by ms609** [comment]
Ooh, thanks, that sounds promising.  Will try it out tonight.

**Comment by GlazerMann** [comment]
I also think that running Maintenance before doing a git pull results in the git pull failure that we are seeing.  You can't pull if you have modified the files.....
