### ISSUE TITLE
Missed opportunity to shorten ResearchGate URL

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#695]
It's a beast, and thus particularly in need of truncation!

https://www.researchgate.net/profile/Johannes_Pignatti/publication/260000370_Pignatti_J_Mariotti_N_1996_-_Systematics_and_phylogeny_of_the_Coleoidea_Cephalopoda_a_comment_upon_recent_works_and_their_bearing_on_the_classification_of_the_Aulacocerida_Palaeopelagos_51995_33-44_Ro/links/0a85e52efcfd97f0d4000000/Pignatti-J-Mariotti-N-1996-Systematics-and-phylogeny-of-the-Coleoidea-Cephalopoda-a-comment-upon-recent-works-and-their-bearing-on-the-classification-of-the-Aulacocerida-Palaeopelagos-51995-33-4.pdf

https://en.wikipedia.org/w/index.php?title=Boletzkyida&type=revision&diff=857239911&oldid=857239682

**Comment by GlazerMann** [comment]
Since gitpull does not work.  Maybe the code does fix this already?

**Comment by ms609** [comment]
Yep!
