### ISSUE TITLE
Wikipedia does not seem to be updating 

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#776]

**Comment by GlazerMann** [comment]
@ms609 any idea why the copies on Wikipedia are not changing?

**Comment by ms609** [comment]
I don't understand the question.  The copies of what?

**Comment by GlazerMann** [comment]
The citation bot on Wikipedia (and dev too) has not updated the git copy in weeks

**Comment by ms609** [comment]
Oh the toolforge installs.  I've manually updated the master.  I'll look into what's going on.  Did a manual visit to ./gitpull.php not work?
