### ISSUE TITLE
Bad data from Zotero?

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#839]
https://en.wikipedia.org/w/index.php?title=Human_evolution&diff=prev&oldid=861465642 -- see last edit on "line 2"

**Comment by GlazerMann** [comment]
https://github.com/zhaofengli/refill  That tool does some extra work on them.
We might want to limit ourselves to only certain websites.

**Comment by GlazerMann** [comment]
probably should now use for google books and jstor and other things that we already do also.

**Comment by GlazerMann** [comment]
That one is fixed
