### ISSUE TITLE
authorN-first= and authorN-last= are not supported

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#892]
In parameters.php these two options are missing from AUTHOR_PARAMETERS and FLATTENED_AUTHOR_PARAMETERS.  I think you have a tool to easily add these.

**Comment by ms609** [comment]
I just use multi-row editing in Notepad++.  I've merged in the changes, accidentally committing straight to the master branch rather than via a PR; I'm hoping that the associated Travis errors reflect issues with the PMID server rather than my edits, though I suspect the latter!
