### ISSUE TITLE
Misses capitals in <Ref> tags

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#900]
https://en.wikipedia.org/w/index.php?title=Asteroxylon&type=revision&diff=863038285&oldid=863038269

missed `<Ref>[doi]</ref>`

Replacing `<Ref>` with `<ref>` caused bot to expand

https://en.wikipedia.org/w/index.php?title=Asteroxylon&type=revision&diff=863038569&oldid=863038285

**Comment by GlazerMann** [comment]
https://github.com/ms609/citation-bot/pull/901
