### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#916]
I think researchgate needs an account cookie.

**Comment by GlazerMann** [comment]
Any idea how Citoid service manages to get access?

**Comment by ms609** [comment]
Is this as simple as setting a curl option to receive and store cookies?

**Comment by GlazerMann** [comment]
I do not know.  I think so.  It is worth a shot.  Might have to go so far as create a dummy account and give zotero that cookie.

**Comment by GlazerMann** [comment]
https://phabricator.wikimedia.org/T93877 It seems like it is possible.   

I do not know how our zotero server is setup.

Also, might need to set referrer url
