### ISSUE TITLE
question: how to resolve a DOI with citation-bot, without actually calling it on a full page?

### ISSUE THREAD

**Issue by monperrus** [ms609/citation-bot#958]
Hi,

I'd like to use only the core feature of citation-bot, the one that transforms a DOI into a wikipedia citation, for instance to transform `10.1002/spe.2249` to

    <ref name="Ortac2015">{{cite journal|last1=Ortac|first1=Alper|last2=Monperrus|first2=Martin|last3=Mezini|first3=Mira|title=Abmash: mashing up legacy Web applications by automated imitation of human actions|journal=Software: Practice and Experience|volume=45|issue=5|year=2015|pages=581–612|issn=00380644|doi=10.1002/spe.2249}}</ref>

How to only resolve a DOI with Citation-bot?

Thanks, --Martin

**Comment by GlazerMann** [comment]
The function is 
function expand_by_doi($template, $force = FALSE) 
If the DOI is not in the crossref database, then we use
function expand_doi_with_dx($template, $doi)

**Comment by monperrus** [comment]
Thanks a lot, I make progress:

```php
include('expandFns.php');
$t = new Template();
$t->add('doi', '10.1002/spe.2249');
expand_by_doi($t);
```

What's the most appropriate function to pretty-print the templace in wiki format (`<ref>{{cite journal...`)?

**Comment by GlazerMann** [comment]
parsed_text()

**Comment by monperrus** [comment]
Thanks, we can expose this super useful function, see #961
